
sudo: required
dist: bionic

language:
  - cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - qtbase5-dev

script:
  - |
    mkdir build || { exit 1; }; \
    cd build || { exit 1; }; \
    cmake -DENABLE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug .. || { exit 1; }; \
    make || { exit 1; }; \
    ctest --output-on-failure || { exit 1; }; \
    make coveralls || { exit 1; };
